#!/usr/bin/env node
// Turns contracts/glyphs.json into the PassType Solidity library.
// Run after scripts/extract-glyphs.py: node scripts/generate-glyphs.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const glyphs = JSON.parse(readFileSync(join(root, 'contracts/glyphs.json'), 'utf8'))

const branches = Object.entries(glyphs)
  .map(([char, { d, adv }]) => `        if (char == "${char}") return ("${d}", ${adv});`)
  .join('\n')

const source = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title PassType
/// @notice Condensed display lettering for the on-chain pass, as vector outlines.
/// @dev Generated by scripts/generate-glyphs.mjs from Archivo (SIL Open Font License 1.1), instanced at
///      weight 800 and width 62. Coordinates are font units on a 1000 unit em, drawn upward from the
///      baseline, so callers scale them with a negative y. A contract cannot load a web font, so the
///      pass carries its own letterforms and matches the site's type wherever it is displayed.
library PassType {
    /// @return path SVG path data for the character, empty when the glyph is not carried.
    /// @return advance How far the cursor moves after drawing, in the same 1000 unit em.
    function glyph(bytes1 char) internal pure returns (string memory path, uint256 advance) {
${branches}
        return ("", 320);
    }
}
`

writeFileSync(join(root, 'contracts/src/PassType.sol'), source)
console.log(`wrote contracts/src/PassType.sol with ${Object.keys(glyphs).length} glyphs`)
